redis:
  image: redis:3.0.3
  restart: always

pg:
  image: postgres:9.3
  restart: always
  environment:
    POSTGRES_PASSWORD: mysecretpassword

rabbitmq:
  image: rabbitmq:3.5.3
  restart: always

logs:
  #build: travis-logs
  image: final-ci/travis-logs:latest
  links:
    - redis:redis
    - pg:postgresql
    - rabbitmq:rabbitmq
  environment:
    ENV: development
  volumes:
    - ./config/travis.yml:/travis.yml
    - /mnt/data:/var/log/finalci/logs

hub:
  #build: travis-hub
  image: final-ci/travis-hub:latest
  links:
    - redis:redis
    - pg:postgresql
    - rabbitmq:rabbitmq
  environment:
    ENV: development
  volumes:
    - ./config/travis.yml:/travis.yml
    - ./config/database.yml:/database.yml
    - ./config/config.yml:/config.yml

api:
  #build: final-api
  image: final-ci/final-api:latest
  links:
    - redis:redis
    - pg:postgresql
    - rabbitmq:rabbitmq
  environment:
    ENV: development
  ports:
    - "55555:55555"
  volumes:
    - ./config/travis.yml:/travis.yml
    - /mnt/data:/var/logs/finalci/logs


worker:
  #build: travis-worker
  image: final-ci/travis-worker:latest
  links:
    - redis:redis
    - pg:postgresql
    - rabbitmq:rabbitmq
  environment:
    ENV: development
  volumes:
    - ./config/worker.yml:/worker.yml
    - /var/run/docker.sock:/var/run/docker.sock
    - ./config/id_rsa:/id_rsa


