defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning
  username: postgres
  port: <%= ENV['POSTGRESQL_PORT_5432_TCP_PORT'] %>
  password: <%= ENV['POSTGRESQL_ENV_POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_PORT_5432_TCP_ADDR'] %>
development:
  <<: *defaults
  database: <%= ENV['FINAL_DATABASE'] %>
  redis:
    url: redis://<%= ENV['REDIS_PORT_6379_TCP_ADDR'] %>:<%= ENV['REDIS_PORT_6379_TCP_PORT'] %>/0

production:
  <<: *defaults
  database: <%= ENV['FINAL_DATABASE'] %>
  redis:
    url: redis://<%= ENV['REDIS_PORT_6379_TCP_ADDR'] %>:<%= ENV['REDIS_PORT_6379_TCP_PORT'] %>/0

test:
  <<: *defaults
  database: <%= ENV['FINAL_DATABASE'] %>
  redis:
    url: redis://<%= ENV['REDIS_PORT_6379_TCP_ADDR'] %>:<%= ENV['REDIS_PORT_6379_TCP_PORT'] %>/0


