env: linux
queue: builds.linux
log_level: debug
sentry:
  dsn: place your dsn here
linux:
  amqp:
    host: <%= ENV['RABBITMQ_PORT_5672_TCP_ADDR'] %>
    port: <%= ENV['RABBITMQ_PORT_5672_TCP_PORT'] %>
    username: guest
    password: guest
    virtual_host: <%= ENV['FINAL_AMQP_VSHOST'] %>
  vms:
    provider: docker
    count: 3
  docker:
    cmd:
#    username: your docker username
    enable_cpuset: true
#    image_name: your image name
#    default_image: your default_image_name
    private_key_path: /id_rsa
    host: localhost
    port: 4243
#  image_override: your image override
  language_mappings:
    haskell: jvm
  queue: builds.linux

